import type { Metadata } from "next";
import "./globals.css";
import { Funnel_Display } from "next/font/google";

const funnelDisplay = Funnel_Display({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        <title>Tu l&apos;as ?</title>
      </head>
      <body className={`${funnelDisplay.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
